### ISSUE TITLE
Code Release ?

### ISSUE THREAD

**Issue by zxfzqf** [kepengxu/PGTFormer#1]
Good work! When will the code be released? Thk

**Comment by 838143396** [comment]
I have already emailed you, could you provide your code, thanks!

**Comment by mmxuan18** [comment]
can share the code and pretrained model?

**Comment by zycheiheihei** [comment]
Same here. I have sent an email. Thanks!

**Comment by kepengxu** [comment]
The code has been released, please let me know if you have any other questions. (●'◡'●)
