### ISSUE TITLE
After the program runs, there is no other information output, and the graphics memory is constantly occupied, but the GPU and CPU usage rates are 0% ？

### ISSUE THREAD

**Issue by amani153** [kepengxu/PGTFormer#11]
(py3.8) PS E:\Studio\PGTFormer-main> python inference_cn.py --input_video=assets/inputdemovideo.mp4 --output_video=exp/output_demo.mp4
C:\Users\PC.conda\envs\py3.8\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be removed in 0.17. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
warnings.warn(
C:\Users\PC.conda\envs\py3.8\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.

![微信图片_20240830110203](https://github.com/user-attachments/assets/5921463e-61ad-48a4-9af3-402f65f074bd)

Environment information:
win11 + py3.8 + cuda11.8 + torch 2.0.1

**Comment by kepengxu** [comment]
It is recommended to use the inference.py file for inference. We have not tested it on Windows. Can you provide more information?😀

**Comment by amani153** [comment]
> It is recommended to use the inference.py file for inference. We have not tested it on Windows. Can you provide more information?😀

I suspect there may be an issue with the installation of the DeepSpeed library, as I encountered the same problem while running other PyTorch programs in the same virtual environment. Therefore, I uninstalled the DeepSpeed library and the PyTorch program was able to run normally.

**Comment by kepengxu** [comment]
https://github.com/kepengxu/PGTFormer/blob/main/easy_inference_in_windows.py
this inference code can solve it
