### ISSUE TITLE
实例的推理结果不一致

### ISSUE THREAD

**Issue by Mr-jie-source** [kepengxu/PGTFormer#12]
你好，感谢代码开源，可以说一下为什么我的复现结果会是这个样子吗？

https://github.com/user-attachments/assets/bbd96d11-717b-46d7-9740-5ec61fd57113

**Comment by eormal** [comment]
你上了个啥，无法播放，你看下文件大小是多少，我复现会出现一直卡主的情况，这个输出视频大小44字节

**Comment by Mr-jie-source** [comment]
> 你上了个啥，无法播放，你看下文件大小是多少，我复现会出现一直卡主的情况，这个输出视频大小44字节

推理的示例视频，视频大小782KB，视频输出颜色与作者的不一致，如下。但刚刚把该视频上传到了飞书，发现颜色正常了，可能与视频编码和播放器有关。
<img width="524" alt="image" src="https://github.com/user-attachments/assets/9fdf6191-4640-4ba6-ab61-4779a514248a">

**Comment by CuddleSabe** [comment]
> 看起来问题解决了😀。

官方提供的解码流程似乎有一些问题，我在外面手动用ffmpeg解码之后来读取图像文件夹，效果就是正常的了
