### ISSUE TITLE
Why the output video is green blackground?

### ISSUE THREAD

**Issue by DerryChan** [kepengxu/PGTFormer#16]
https://github.com/user-attachments/assets/3e961208-fe95-4376-8343-38971a4f7467

<img width="702" alt="image" src="https://github.com/user-attachments/assets/8691dd1c-924f-479e-a457-e20adb624beb">

py=3.8, torch=2.0.1

**Comment by kepengxu** [comment]
hello
i cant open this MP4
and may be you need to play this video on other video players.

**Comment by asrays** [comment]
@DerryChan modify ffmpeg_output in inference.py with the following code
```
    ffmpeg_output = [
    'ffmpeg_lib/ffmpeg', '-y',
    '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-s', f'{width}x{height}', '-r', str(fps),
    '-i', '-', '-an',
    '-pix_fmt', 'yuv420p',  # Enforce a standard pixel format for codecs
    '-color_range', 'pc',   # "pc" for full range (0-255), vs "tv" for limited (16-235)
    '-vcodec', 'libx264',   # Try x264 instead of x265 if color fidelity matters more
    '-crf', '18',
    '-preset', 'fast',
    output_path
]
```
