### ISSUE TITLE
可以处理分辨率非（512，512）的视频吗？

### ISSUE THREAD

**Issue by laulampaul** [kepengxu/PGTFormer#6]
您好，
我想处理分辨率（256，256）的视频时候，发现报错，经过定位后，发现是
feat_out32 注释了，torch.cat([feat_out,feat_out16,feat_out32],1)维度不对齐，请问该算法可以处理分辨率非（512，512）的视频吗，应该怎么改，谢谢！

feat_out = F.interpolate(feat_out, (32, 32), mode='bilinear', align_corners=True)
feat_out16 = F.interpolate(feat_out16, (32, 32), mode='bilinear', align_corners=True)
# feat_out32 = F.interpolate(feat_out32, (32, 32), mode='bilinear', align_corners=True)
outf = torch.cat([feat_out,feat_out16,feat_out32],1)

**Comment by kepengxu** [comment]
Hello
Thanks for using it.
A simple way is to pre-sample the video (like opencv or ffmpeg) to 512.
ffmpeg -i input_video.mp4 -vf "scale=512:512" output_video.mp4

But be careful to make sure the distribution ratio of the face is similar to the test video. Do not make the face ratio too small or too large, which will affect the recovery quality.

Please contact me if you have any questions. (*^_^*)
