### ISSUE TITLE
How large the degradation you set?

### ISSUE THREAD

**Issue by CuddleSabe** [kepengxu/PGTFormer#8]
<img width="992" alt="截屏2024-08-29 15 48 34" src="https://github.com/user-attachments/assets/d87dd8d8-a651-479f-a0e0-852fd5d3f66e">

the left is 512GPEN, the mid is input , and the right is PGTFormer
May I ask the degradation parameters?

**Comment by kepengxu** [comment]
There are two reasons for this phenomenon:
1. Different degradation strategies.
2. I guess your GPEN is trained on FFHQ. The FFHQ dataset has more details, and the trained model has richer details.
3. 
I directly use the degradation code provided by VFHQ. https://liangbinxie.github.io/projects/vfhq/

**Comment by kepengxu** [comment]
3. This version of the weight is suitable for non-aligned face videos. It can be found in the paper that various indicators such as PSNR are significantly disadvantaged in non-aligned cases.
